"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
import sys
import dj_database_url
from dotenv import load_dotenv

# .env 는 mirisalpim-web/ 루트 하나만 읽는다 (.env.example·ai_core/config.py 와 같은 위치).
# 인자 없는 load_dotenv() 는 backend/config/ 부터 위로 거슬러 올라가며 찾기 때문에,
# backend/.env 가 생기면 그쪽이 먼저 잡혀 설정이 두 곳으로 갈라진다.
load_dotenv(Path(__file__).resolve().parents[2] / ".env")
IS_TEST = "test" in sys.argv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
FRONTEND_DIST = BASE_DIR / "frontend_dist"

# ai_core 는 backend/ 바깥(mirisalpim-web/ai_core)에 있고 Django 의존이 없다.
# Django 프로세스는 import 만 하므로 경로만 추가한다 (CLI 단독 실행은 그대로 가능).
REPO_ROOT = BASE_DIR.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

# 시나리오 카드 원본 (seed_scenarios 관리 명령이 읽는다).
# mirisalpim-web/data/scenarios/ — 배포 저장소 안에 있어야 한다. 예전에는
# REPO_ROOT.parent/scenario/json_data(별도 저장소 AI_challenge/scenario/)를 가리켜서
# mirisalpim-web 단독 체크아웃(Railway 등)에서는 존재하지 않는 경로였다.
SCENARIO_SEED_DIR = Path(
    os.environ.get("SCENARIO_SEED_DIR", REPO_ROOT / "data" / "scenarios")
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["SECRET_KEY"]
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"


def _int_env(name, default):
    """정수 환경변수. 잘못된 값이면 경고만 남기고 기본값으로 계속 뜬다.

    ⚠️ 여기서 int() 가 그대로 ValueError 를 올리면 settings import 가 끊겨
    워커가 부팅 중에 죽는다 - 첫 요청에 500 이 나는 게 아니라 크래시 루프가 된다
    (ai_core/llm.py 의 validate_config() 와 같은 종류의 함정). Railway 변수 UI 에
    "86400 # 하루" 처럼 주석을 같이 적는 실수가 배포를 통째로 막으면 안 된다.
    """
    raw = os.environ.get(name)
    if raw is None:
        return default
    try:
        return int(raw)
    except ValueError:
        print(f"[설정 경고] {name}={raw!r} 가 정수가 아니어서 {default} 를 사용합니다.")
        return default


# 음성 레이턴시 벤치마크가 요청한 경우에만 상세 SSE timing 이벤트를 노출한다.
# 단계별 서버 로그는 원문·사용자 식별자 없이 항상 남지만, API 응답의 내부 지표는
# 운영에서 명시적으로 켜지 않는 한 숨긴다.
VOICE_LATENCY_DIAGNOSTICS = (
    os.environ.get("VOICE_LATENCY_DIAGNOSTICS", "False").lower() == "true"
)
OPENING_AUDIO_CACHE_SECONDS = _int_env("OPENING_AUDIO_CACHE_SECONDS", 86400)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "ALLOWED_HOSTS",
        "localhost,127.0.0.1,.up.railway.app",
    ).split(",")
    if host.strip()
]
if IS_TEST and "testserver" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("testserver")

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "CSRF_TRUSTED_ORIGINS",
        "https://*.up.railway.app",
    ).split(",")
    if origin.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "training"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [FRONTEND_DIST],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'  # 턴 SSE 에 async view 를 쓴다


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DATABASE_URL"),
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# 캐시
# 기본값(LocMemCache, MAX_ENTRIES=300)을 그대로 쓰면 opening TTS 캐시가 레이트리밋·
# 멱등성 키와 300칸을 나눠 쓴다. 실측하면 경쟁 엔트리가 약 238개를 넘는 순간
# 컬링이 오래된 키부터 반복 적용돼 voice opening 62개가 한 번에 전부 날아간다
# (점진적 감소가 아니라 절벽이다). 그러면 세션 시작마다 TTS 를 다시 기다린다.
# 값 62개를 다 담아도 5MB 남짓이라 한도를 올리는 편이 싸다.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "mirisalpim-default",
        "OPTIONS": {"MAX_ENTRIES": 2000},
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [FRONTEND_DIST] if FRONTEND_DIST.exists() else []


SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# 익명 세션 TTL (API 설계 9절: 30분 비활성).
# SESSION_SAVE_EVERY_REQUEST 가 있어야 '마지막 요청 기준 30분'이 된다.
SESSION_COOKIE_AGE = 1800
SESSION_SAVE_EVERY_REQUEST = True

SECURE_SSL_REDIRECT = not DEBUG and not IS_TEST
SECURE_HSTS_SECONDS = 0  # 초기 배포 검증 후 점진적으로 활성화


# 로깅
# Railway 는 컨테이너 stdout 을 그대로 수집하므로 콘솔 핸들러 하나면 된다.
# error_response 가 만드는 requestId 를 여기로 흘려보내야 배포 후에 "사용자가 본
# 오류"와 "서버 로그"를 맞춰볼 수 있다. 그게 없으면 requestId 는 장식일 뿐이다.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        # 테스트는 4xx·5xx 를 일부러 만들어 검증한다. 그 로그가 그대로 찍히면
        # 실제 실패가 묻히므로 테스트에서만 잠재운다.
        "training": {"level": "CRITICAL" if IS_TEST else "INFO"},
        "django.request": {"level": "CRITICAL" if IS_TEST else "WARNING"},
    },
}
