# Generated by Django 6.1 on 2026-08-16 12:41

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS vector;"),
        
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anon_client_id', models.CharField(max_length=100)),
                ('entry_path', models.CharField(choices=[('recommended', 'AI 추천'), ('direct', '직접 선택')], max_length=20)),
                ('turn', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', '진행 중'), ('ended', '종료')], max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvalResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anon_client_id', models.CharField(max_length=100)),
                ('phase', models.CharField(choices=[('pre', '사전'), ('post', '사후')], max_length=4)),
                ('score', models.PositiveSmallIntegerField()),
                ('total_questions', models.PositiveSmallIntegerField()),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('scenario_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('voice', '보이스피싱'), ('smishing', '스미싱'), ('phishing', '피싱')], max_length=20)),
                ('track', models.CharField(choices=[('teen', '청소년'), ('young', '청년'), ('parent', '중장년'), ('senior', '노년')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('source', models.TextField()),
                ('is_scam', models.BooleanField(default=True)),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('goal', models.TextField()),
                ('max_turns', models.PositiveSmallIntegerField(default=20)),
                ('persona_name', models.CharField(max_length=100)),
                ('persona_org', models.CharField(max_length=200)),
                ('persona_tone', models.TextField()),
                ('persona_voice_preset', models.CharField(max_length=50)),
                ('forbidden', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('utterance_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('scam_type', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=50)),
                ('tactic', models.CharField(max_length=100)),
                ('context', models.TextField(blank=True)),
                ('source', models.CharField(max_length=200)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisReport',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='diagnosis', serialize=False, to='training.session')),
                ('vulnerability_type', models.CharField(max_length=30)),
                ('missed_tell_points', models.JSONField(default=list)),
                ('guidance_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserJudgment',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='judgment', serialize=False, to='training.session')),
                ('judged_turn', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_scam_guess', models.BooleanField()),
                ('grade', models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('오탐', '오탐')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskyAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_no', models.PositiveSmallIntegerField()),
                ('action_type', models.CharField(choices=[('personal_info', '개인정보제공'), ('link_click', '링크클릭'), ('app_install', '앱설치동의'), ('transfer_consent', '송금동의'), ('isolation_accepted', '고립수용')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risky_actions', to='training.session')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='training.scenario'),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_key', models.CharField(max_length=50)),
                ('order_index', models.PositiveSmallIntegerField()),
                ('objective', models.TextField()),
                ('opening', models.TextField(blank=True, null=True)),
                ('min_turns', models.PositiveSmallIntegerField(default=1)),
                ('tactics', models.JSONField(default=list)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='training.scenario')),
            ],
            options={
                'unique_together': {('scenario', 'stage_key')},
            },
        ),
        migrations.AddField(
            model_name='session',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='training.stage'),
        ),
        migrations.CreateModel(
            name='TellPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tp_key', models.CharField(max_length=20)),
                ('trigger', models.TextField()),
                ('why', models.TextField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('first_detectable_turn', models.PositiveSmallIntegerField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tell_points', to='training.scenario')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tell_points', to='training.stage')),
            ],
            options={
                'unique_together': {('scenario', 'tp_key')},
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_no', models.PositiveSmallIntegerField()),
                ('role', models.CharField(choices=[('scammer', '사기범'), ('user', '훈련생')], max_length=10)),
                ('text', models.TextField()),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='training.session')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='training.stage')),
            ],
        ),
        migrations.CreateModel(
            name='SessionTellPointHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit_turn', models.PositiveSmallIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tell_point_hits', to='training.session')),
                ('tell_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='training.tellpoint')),
            ],
            options={
                'unique_together': {('session', 'tell_point')},
            },
        ),
    ]
