# Generated by Django 6.1 on 2026-08-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='resistance_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='turns_in_stage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
