# Generated by Django 6.1 on 2026-08-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_session_resistance_count_session_turns_in_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisreport',
            name='strength',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diagnosisreport',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diagnosisreport',
            name='weakness',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='diagnosisreport',
            name='vulnerability_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
