# Generated by Django 6.1 on 2026-08-30 15:31

import django.utils.timezone
from django.db import migrations, models


def discard_existing_ended_transcripts(apps, schema_editor):
    """이전 자동 종료 경로가 남긴 원문도 배포 즉시 파기한다.

    판단 없이 ended가 된 세션은 리포트가 없으므로 expired로 구분한다. 그래야
    클라이언트가 존재하지 않는 결과 화면으로 이동하지 않고 새 훈련을 안내한다.
    """
    Session = apps.get_model("training", "Session")
    Turn = apps.get_model("training", "Turn")
    UserJudgment = apps.get_model("training", "UserJudgment")

    judged_session_ids = UserJudgment.objects.values_list("session_id", flat=True)
    Session.objects.filter(status="ended").exclude(
        session_id__in=judged_session_ids
    ).update(status="expired")
    Turn.objects.filter(session__status__in=("ended", "expired")).exclude(
        text=""
    ).update(text="")


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_diagnosisreport_strength_diagnosisreport_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='last_activity_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('active', '진행 중'), ('awaiting_judgment', '최종 판단 대기'), ('judging', '최종 판단 처리 중'), ('ended', '종료'), ('expired', '만료')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status', 'last_activity_at'], name='training_s_status_4e2c_idx'),
        ),
        migrations.RunPython(
            discard_existing_ended_transcripts,
            migrations.RunPython.noop,
        ),
    ]
