# Generated by Django 6.1 on 2026-08-19 13:54

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    """RAG 도입 시에만 실행된다 — rag 앱은 INSTALLED_APPS 에 없다 (rag/models.py 참고).

    vector extension 생성이 여기 있으므로 초기 배포는 pgvector 없이도 성공한다.
    """

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('utterance_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('scam_type', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=50)),
                ('tactic', models.CharField(max_length=100)),
                ('context', models.TextField(blank=True)),
                ('source', models.CharField(max_length=200)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
            ],
        ),
    ]
